[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#9699a8"
yellow = "#e0af68"

[colors.primary]
background = "#0C060D"
foreground = "#a9b1d6"
[window]
padding = { x = 10, y = 8 }

[font]
size = 10.0
normal = { family = 'JetBrainsMono Nerd Font Mono', style = 'Regular' }
bold = { family = 'JetBrainsMono Nerd Font Mono', style = 'Bold' }
italic = { family = 'JetBrainsMono Nerd Font Mono', style = 'Italic' }
bold_italic = { family = 'JetBrainsMono Nerd Font Mono', style = 'Bold Italic' }

[cursor.style]
shape = "Beam"
blinking = "On"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = '\x1b\r'
